FROM golang:1.25.0-alpine3.22 AS builder

RUN apk add --no-cache git

WORKDIR /build

COPY app/go.mod app/go.sum* ./
RUN go mod download

COPY app/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o /build/app \
    main.go

FROM scratch

COPY --from=builder /build/app /app

CMD ["/app"]
