FROM openjdk:24-ea-jdk-bookworm AS builder

WORKDIR /build

COPY app/gradle ./gradle
COPY app/gradlew .
COPY app/gradle.properties .
COPY app/build.gradle .
COPY app/settings.gradle .
RUN ./gradlew dependencies --no-daemon
COPY app/src ./src
RUN ./gradlew bootJar --no-daemon

FROM openjdk:24-ea-jdk-slim-bookworm

COPY --from=builder /build/build/libs/*.jar /app.jar

CMD ["java", "-jar", "/app.jar"]
