FROM python:3.13.7-alpine3.22

RUN pip install "fastapi[standard]==0.116.1"

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app .

CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]

