FROM python:3.13.7-alpine3.22

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install Django==5.2.6

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app.wsgi:application"]
