FROM rust:1.89.0-alpine3.22 AS builder

RUN apk add --no-cache musl-dev pkgconfig openssl-dev

WORKDIR /build

COPY app/Cargo.toml app/Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
RUN rm -rf src

COPY app/src ./src
RUN touch src/main.rs && cargo build --release

FROM alpine:3.22
RUN apk add --no-cache libgcc
WORKDIR /app
COPY --from=builder /build/target/release/app .

CMD ["./app"]
